-- MySQL Script generated by MySQL Workbench
-- Thu Dec 12 23:38:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8mb3 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`Cubiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Cubiculos` (
  `idCubiculo` INT NOT NULL,
  `ocupado` BLOB NOT NULL,
  PRIMARY KEY (`idCubiculo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `biblioteca`.`Salas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Salas` (
  `idSala` INT NOT NULL,
  `ocupada` BLOB NOT NULL,
  PRIMARY KEY (`idSala`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `biblioteca`.`Sensores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Sensores` (
  `idSensor` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSensor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `biblioteca`.`LecturaSensores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`LecturaSensores` (
  `idLectura` INT NOT NULL AUTO_INCREMENT,
  `idSensor` INT NOT NULL,
  `valor` INT NULL DEFAULT NULL,
  `idCubiculo` INT NULL DEFAULT NULL COMMENT 'Null si la lectura pertenece a una sala',
  `idSala` INT NULL DEFAULT NULL COMMENT 'Null si la lectura pertenece a un cubículo',
  `fechaHora` DATETIME NOT NULL,
  PRIMARY KEY (`idLectura`),
  INDEX `idSala_idx` (`idSala` ASC) VISIBLE,
  INDEX `idCubiculo_idx` (`idCubiculo` ASC) VISIBLE,
  INDEX `idSensor_idx` (`idSensor` ASC) VISIBLE,
  CONSTRAINT `idCubiculo`
    FOREIGN KEY (`idCubiculo`)
    REFERENCES `biblioteca`.`Cubiculos` (`idCubiculo`),
  CONSTRAINT `idSala`
    FOREIGN KEY (`idSala`)
    REFERENCES `biblioteca`.`Salas` (`idSala`),
  CONSTRAINT `idSensor`
    FOREIGN KEY (`idSensor`)
    REFERENCES `biblioteca`.`Sensores` (`idSensor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `biblioteca`.`Tarjetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Tarjetas` (
  `idTarjeta` INT NOT NULL,
  PRIMARY KEY (`idTarjeta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `biblioteca`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `passw` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `tipo` BLOB NOT NULL,
  `idTarjeta` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `email`),
  INDEX `fk_Usuarios_Tarjetas1_idx` (`idTarjeta` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Tarjetas1`
    FOREIGN KEY (`idTarjeta`)
    REFERENCES `biblioteca`.`Tarjetas` (`idTarjeta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `biblioteca`.`Reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Reservas` (
  `idReservas` INT NOT NULL AUTO_INCREMENT,
  `email_usuario` VARCHAR(45) NOT NULL,
  `idSala` INT NOT NULL,
  `horaReserva` DATETIME NULL,
  PRIMARY KEY (`idReservas`),
  INDEX `email_usuario_idx` (`email_usuario` ASC) VISIBLE,
  INDEX `idSala_idx` (`idSala` ASC) VISIBLE,
  CONSTRAINT `email_usuario`
    FOREIGN KEY (`email_usuario`)
    REFERENCES `biblioteca`.`Usuarios` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idSala`
    FOREIGN KEY (`idSala`)
    REFERENCES `biblioteca`.`Salas` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
